language: node_js
node_js:
    - "stable"
before_script:
    - ./node_modules/.bin/pm2 start -f test/server/server.js --name=obsidian-proxy-server-test &
script:
    - grunt jshint browserify:test mocha_phantomjs
after_script:
    - ./node_modules/.bin/pm2 kill
